### ISSUE TITLE
No camera image

### ISSUE THREAD

**Issue by Lu7913** [hofbi/telecarla#17] opened 2021-01-18 13:31 UTC
Hi, 
First I had the same problem as seen here #6, catkin make instead of catkin build solved the issue, or inserting the package in exiting ROS-bridge workspace also worked.
Now the problem is that when i  roslaunch telecarla telecarla_single_local.launch or any other launch file, I get no camera image back. (telecarla_manual_control, pygame hud is opened all the text is here but no image form camera). There is no error being shown, everything looks normal. ROS-bridge works fine. Any hint where to look for the possible problem, would be great.

Best regards 

Using:
Kubuntu 18.04
Carla 9.10.1
python2

**Comment by hofbi** [comment] 2021-01-18 13:55
Which version of the ROS bridge are you using? Is it also [9.10.1](https://github.com/carla-simulator/ros-bridge/releases/tag/0.9.10.1)? I know that on the latest master there were some breaking changes in the sensor creation and renaming of topic names which is currently not integrated in telecarla as they are still ongoing. But with the release it should work.

If not, what happens if you run `roslaunch carla_ros_bridge carla_ros_bridge_with_example_ego_vehicle.launch`. If this also opens a UI window without showing the image, then the issue is related to the ros bridge itself. If you see a valid image here you could try a `rostopic info` to see under which topic the ros bridge is publishing the image.

**Comment by Lu7913** [comment] 2021-01-18 14:52
I'm using ROS melodic, ROS bridge is the latest master. Launching example mentioned above works normally (apart of awful framerate that I am getting due to some problems with synchronous mode), image from camera is visible. Image is posted to _/carla/ego_vehicle/camera/rgb/front/image_color_, which is also on the list, when running telecarla example.
I have just tried with ROS bridge 9.10.1 with same results, but now, there is an error, when launching telecarla example: _Sensor sensor.camera.rgb/front will not be spawned, attribute 'height' not found_ . I will try with 9.10. If that helps, otherwise I will add an attribute. 

One more question: I'm quite now to the ROS, so I'm a bit confused, should I watch for some problems when sourcing telecarla workspace? Should I have ros bridge and telecara workspaces combined/extended? Or sourcing just telecarla works fine? 

Thank you.

**Comment by hofbi** [comment] 2021-01-18 16:10
Ok so not directly sure what might cause this problem. I will try myself if I can reproduce it using the same versions.

When you change the ros bridge version, do you also change the related python API carla egg file?

You should only have a single workspace. Either have both, the carla ros bridge and telecarla in the same workspace if you build the ros bridge from source. If you followed the telecarla [setup iknstructions](https://github.com/hofbi/telecarla#setup), the ros bridge will be installed from its ppa. This means you don't to have it in your workspace, but you need to additionally `source /opt/carla-ros-bridge/melodic/setup.bash`

**Comment by Lu7913** [comment] 2021-01-18 21:24
I have also tried with Carla 9.10 and ROS bridge [https://github.com/carla-simulator/ros-bridge/commit/ee524bb50a7328402b4fe537a7e92d7927020bf8](url), again no picture from the camera and no error. I know some changes were made to camera attributes in rosbridge, after latest telecarla commit. 

> When you change the ros bridge version, do you also change the related python API carla egg file

Depends on the ROS bridge version I'm trying to work with. For the latest test I tried with carla 9.10 and rosbridge commit about that time. 

> You should only have a single workspace. Either have both, the carla ros bridge and telecarla in the same workspace if you build the ros bridge from source. If you followed the telecarla setup iknstructions, the ros bridge will be installed from its ppa. This means you don't to have it in your workspace, but you need to additionally source /opt/carla-ros-bridge/melodic/setup.bash

Yes, if I understand correctly sourcing telecarla then overrides rosbridge workspace, unless you extend one?

**Comment by hofbi** [comment] 2021-01-19 10:46
I found the issue. In carla 0.9.10.1 the sensor config for defining camera `widht` and `height` has been changed to `image_size_x` and `image_size_y`. I opened the PR #18 which contains the fix. Could you try if it works for you with this fix. Once you config I will merge this PR.

**Comment by Lu7913** [comment] 2021-01-19 11:42
I have tried with Carla 0.9.10.1, ROS bridge 0.9.10.1 and latest telecarla, I still got: `[FATAL] : Sensor will not be spawned, because sensor spec is invalid: ''width''
`

**Comment by Lu7913** [comment] 2021-01-20 08:54
I have tried with Carla 0.9.10.1, ROS bridge 0.9.10.1 and latest telecarla and I got: `[FATAL] :Sensor will not be spawned, because sensor spec is invalid: ''width''`

**Comment by Lu7913** [comment] 2021-01-20 10:16
> 
> 
> But this is exactly the fix I provide with #18. Did you used the branch `carla_0_9_10_1` or latest master of telecarla?

I checked two times, reinstall everything,  installed correct .egg files, since it was weird to me too. I will try again today, delete all other Carla version i have installed, but I doubt it will be any better, but I leave the possibility. I will try with precompiled releases.

**Comment by hofbi** [comment] 2021-01-20 10:23
You don't need to change the carla version itself. I created a branch in this repo named `carla_0_9_10_1` as it contains the fixes for this carla version. I wanted to know if you used telecarla on branch `master` or if you tried the branch `carla_0_9_10_1`?

**Comment by Lu7913** [comment] 2021-01-20 10:28
Of course I used carla_0_9_10_1 branch, the error message is different or should I say there is a error message, when I used master telecarla master branch, there was no message. I just wanted to point out that I used the correct Carla version.

**Comment by hofbi** [comment] 2021-01-20 11:34
> I have tried with Carla 0.9.10.1, ROS bridge 0.9.10.1 and latest telecarla and I got: [FATAL] :Sensor will not be spawned, because sensor spec is invalid: ''width''

I tired to reproduce you issue again, but I failed. The error itself is already strange as this is exactly the error that should be fixed on the branch and on my machine it works. The only way why this error still appears could be some build artefacts.

**Comment by Lu7913** [comment] 2021-01-20 13:06
I reinstalled everything and it works. I'm sorry for the inconvenience. You can close the issue.

**Comment by Lu7913** [comment] 2021-01-20 13:08
I reinstalled everything and it works now. I'm sorry for the inconvenience and thank you for you help. You can close the issue now.

**Closed** 2021-01-20 14:06 UTC

**Comment by hofbi** [comment] 2021-01-20 14:14
Thanks for reporting. I merged the PR and added a tag to simplify the the link of CARLA version and TELECARLA version.
